# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZFJdX70lhT5147cYg1F6gA2VxRWo9cZ
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scale-dependent spacetime geometry: Yukawa toolkit

Este script implementa:
- Potencial Yukawa
- Precesión de perihelio (corrección Yukawa sobre el potencial newtoniano)
- Deflexión de luz
- Energía efectiva ρ_eff(r) (ilustrativa)
- Forecast Gaia muy simplificado
- Generación de yukawa_constraints.pdf y rho_eff_yukawa.pdf
- Tests básicos de validación

Requisitos:
- numpy
- scipy
- matplotlib
"""

import numpy as np
from dataclasses import dataclass
from typing import Tuple, Callable

from scipy.integrate import quad
import matplotlib.pyplot as plt

# --- Constantes físicas (SI) ---
G0 = 6.67430e-11      # m^3 kg^-1 s^-2
c0 = 2.99792458e8     # m/s
M_sun = 1.98847e30    # kg
AU = 1.495978707e11   # m
R_sun = 6.9634e8      # m

@dataclass
class YukawaParams:
    alpha: float      # alpha_Y
    lambda_m: float   # lambda_Y [m]

# --- Potencial Yukawa ---

def phi_yukawa(r: float, M: float, params: YukawaParams) -> float:
    """
    Potencial gravitatorio con corrección Yukawa.
    Phi(r) = - G M / r * (1 + alpha * exp(-r/lambda))
    """
    if r <= 0:
        raise ValueError(f"r must be > 0, got {r}")
    return -G0 * M / r * (1.0 + params.alpha * np.exp(-r / params.lambda_m))

# --- Derivada numérica: extrapolación de Richardson ---

def _richardson_derivative(f: Callable[[float], float],
                           x: float,
                           h: float,
                           order: int = 2) -> float:
    """
    Derivada f'(x) usando diferencias centrales + extrapolación de Richardson.

    Nota sobre h:
    - Si h es demasiado pequeño, se produce cancelación catastrófica.
    - Regla heurística en doble precisión: h ~ 1e-5 * max(|x|, 1).
    """
    if h <= 0:
        raise ValueError("h must be positive")
    D = []
    for k in range(order + 1):
        hk = h / (2.0 ** k)
        Dk = (f(x + hk) - f(x - hk)) / (2.0 * hk)
        D.append(Dk)
    # Extrapolación de Richardson
    for m in range(1, order + 1):
        for k in range(order, m - 1, -1):
            D[k] = D[k] + (D[k] - D[k - 1]) / (4 ** m - 1)
    return D[order]

# --- Precesión de perihelio Yukawa ---

def perihelion_precession_yukawa(a: float,
                                 e: float,
                                 M: float,
                                 params: YukawaParams,
                                 h_e: float = 1e-4) -> float:
    """
    Precesión adicional de perihelio debida EXCLUSIVAMENTE a la corrección
    Yukawa en Phi(r), sobre el potencial newtoniano puro.

    Es decir, devuelve Δϖ_Yukawa (corrección), NO la precesión total GR.

    Por construcción:
    - Si alpha = 0  -> Δϖ_Yukawa ≈ 0.
    """
    if not (0.0 <= e < 1.0):
        raise ValueError(f"Eccentricity must be in [0,1), got e={e}")
    R_s = 2.0 * G0 * M / c0**2
    if a <= 5.0 * R_s:
        raise ValueError("a too close to Schwarzschild radius; weak-field approximation breaks down")

    def avg_delta_phi(ecc: float) -> float:
        # r(f) = a(1-e^2)/(1+e cos f)
        def integrand(f):
            r = a * (1.0 - ecc**2) / (1.0 + ecc * np.cos(f))
            phiY = phi_yukawa(r, M, params)
            phiN = -G0 * M / r
            deltaPhi = phiY - phiN
            return deltaPhi
        res, err = quad(integrand, 0.0, 2.0*np.pi, epsabs=0, epsrel=1e-8)
        return res / (2.0 * np.pi)

    def f_e(ecc: float) -> float:
        return avg_delta_phi(ecc)

    n = np.sqrt(G0 * M / a**3)
    # Derivada numérica de <deltaPhi> respecto de e
    h_loc = h_e
    if e < 1e-3:
        # Evitar pasar a e<0
        e_plus = e + h_loc
        e_minus = max(e - h_loc, 0.0)
        d_avg_de = (f_e(e_plus) - f_e(e_minus)) / (e_plus - e_minus)
    else:
        d_avg_de = _richardson_derivative(f_e, e, h_loc, order=2)

    Delta_varpi = -(1.0 / (n * a**2 * e)) * d_avg_de
    return Delta_varpi

# --- Deflexión de luz Yukawa ---

def deflection_angle_yukawa(b: float,
                            M: float,
                            params: YukawaParams,
                            gamma_inf: float = 1.0) -> Tuple[float, float]:
    """
    Deflexión total para un rayo de luz con impacto b, en el ansatz Yukawa
    con Psi = gamma_inf * Phi (minimal ansatz).

    Devuelve (alpha_total, alpha_GR), ambos en radianes.
    """
    if b <= 0:
        raise ValueError("Impact parameter b must be > 0")

    # Deflexión GR (siempre la misma para comparación)
    alpha_gr = 4.0 * G0 * M / (c0**2 * b)

    # Calculate alpha_total
    if params.alpha == 0.0:
        # For alpha=0, phi_yukawa reduces to the Newtonian potential -G0*M/r.
        # The derivative d/dr[(1+gamma_inf)*Phi_Newtonian] can be calculated analytically.
        # integrand_alpha_zero is d/dr[(1+gamma_inf)*(-G0*M/r)] * b/r
        # which is (1+gamma_inf)*G0*M/r^2 * b/r
        def integrand_alpha_zero(z: float) -> float:
            r = np.sqrt(b**2 + z**2)
            dPhi_dR_analytic = (1.0 + gamma_inf) * G0 * M / (r**2)
            return dPhi_dR_analytic * b / r
        res, err = quad(integrand_alpha_zero, -1e11, 1e11, epsabs=0, epsrel=1e-6)
        alpha_tot = 2.0 * res / c0**2
    else:
        # For general alpha, use numerical differentiation
        def phi_plus_psi(r: float) -> float:
            phi = phi_yukawa(r, M, params)
            psi = gamma_inf * phi
            return phi + psi  # Equivalent to (1+gamma_inf)*Phi

        def integrand_general(z: float) -> float:
            r = np.sqrt(b**2 + z**2)
            h_val = 1e3
            dPhi_dR = (phi_plus_psi(r + h_val) - phi_plus_psi(r - h_val)) / (2.0 * h_val)
            return dPhi_dR * b / r
        res, err = quad(integrand_general, -1e11, 1e11, epsabs=0, epsrel=1e-6)
        alpha_tot = 2.0 * res / c0**2

    return alpha_tot, alpha_gr

# --- Energía efectiva (ilustrativo) ---

def rho_eff_yukawa_r(r: float,
                     M: float,
                     params: YukawaParams) -> float:
    """
    Densidad de energía efectiva ρ_eff(r) en el régimen débil para el ansatz
    Yukawa, aproximando A(r) ≈ 1 + 2Phi/c^2, B(r) ≈ 1 - 2Phi/c^2.

    Esta función es ilustrativa; para r >> R_s.
    """
    # Aproximación Poissoniana efectiva:
    # ∇^2 Phi_eff = 4π G0 rho_eff
    # En esfericidad: (1/r^2) d/dr (r^2 dPhi/dr) = 4π G0 rho_eff
    def Phi_r(x):
        return phi_yukawa(x, M, params)
    h = 1e-3 * r
    if h <= 0:
        h = 1e3
    dPhi_dr = (Phi_r(r + h) - Phi_r(r - h)) / (2*h)
    d2Phi_dr2 = (Phi_r(r + h) - 2*Phi_r(r) + Phi_r(r - h)) / (h**2)
    laplacian = d2Phi_dr2 + (2.0 / r) * dPhi_dr
    rho_eff = laplacian / (4.0 * np.pi * G0)
    return rho_eff

# --- Plot: constraints Yukawa (esquemático realista) ---

def make_yukawa_constraints_plot(filename: str = "yukawa_constraints.pdf") -> None:
    """
    Genera una figura esquemática de constraints en (lambda_Y, alpha_Y).
    """
    lam = np.logspace(-4, 2, 200)  # en unidades de AU
    # Líneas esquemáticas (no son fits exactos)
    alpha_cassini = 2.3e-5 * np.ones_like(lam)
    alpha_mercury = 1e-4 * np.ones_like(lam)
    alpha_torsion = 1e-2 * (lam / 1e-4)**0.5
    alpha_gaia = 1e-4 * np.ones_like(lam)

    plt.figure(figsize=(6,4.5))
    plt.loglog(lam, alpha_cassini, label="Cassini (γ)", ls="--")
    plt.loglog(lam, alpha_mercury, label="Mercury perihelion", ls="-.")
    plt.loglog(lam, alpha_torsion, label="Torsion balance", ls=":")
    plt.loglog(lam, alpha_gaia, label="Gaia-like forecast", ls="-")

    plt.xlabel(r"$\lambda_{\mathrm{Y}}\,[\mathrm{AU}]$")
    plt.ylabel(r"$|\alpha_{\mathrm{Y}}|$")
    plt.ylim(1e-6, 1e0)
    plt.xlim(1e-4, 1e2)
    plt.grid(True, which="both", ls=":")
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()

# --- Plot: rho_eff(r) ---

def plot_rho_eff_yukawa(filename: str = "rho_eff_yukawa.pdf") -> None:
    """
    Genera un plot de ρ_eff(r) / ρ_GR(r) para tres valores de alpha_Y.
    """
    M = M_sun
    r_grid = np.logspace(-2, 1, 200) * AU  # 0.01 AU a 10 AU
    alphas = [-1e-4, 0.0, 1e-4]
    colors = ["C0", "C1", "C2"]

    plt.figure(figsize=(6,4.5))
    for alpha, col in zip(alphas, colors):
        params = YukawaParams(alpha=alpha, lambda_m=0.1 * AU)
        rho_eff_vals = []
        rho_eff_gr_vals = []
        for r in r_grid:
            params0 = YukawaParams(alpha=0.0, lambda_m=0.1*AU)
            rho_eff = rho_eff_yukawa_r(r, M, params)
            rho_eff_gr = rho_eff_yukawa_r(r, M, params0)
            rho_eff_vals.append(rho_eff)
            rho_eff_gr_vals.append(rho_eff_gr)
        # Avoid division by zero if rho_eff_gr_vals contains zeros
        ratio = np.array(rho_eff_vals) / np.where(np.array(rho_eff_gr_vals) == 0, 1e-30, np.array(rho_eff_gr_vals))
        plt.loglog(r_grid / AU, ratio, label=rf"$\alpha_{{\mathrm{{Y}}}}={alpha:.4f}$", color=col)

    plt.xlabel(r"$r\, [\mathrm{AU}]$")
    plt.ylabel(r"$\rho_{\mathrm{eff}}(r)/\rho_{\mathrm{GR}}(r)$")
    plt.grid(True, which="both", ls=":")
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()

# --- Tests de validación ---

def test_yukawa_zero_limit() -> None:
    """
    Verifica que la corrección Yukawa tiende a 0 cuando alpha -> 0.

    Es decir, para alpha = 0, la precesión adicional Δϖ_Yukawa debe
    ser numéricamente muy pequeña.
    """
    a = 0.387 * AU   # órbita de Mercurio aproximada
    e = 0.2056
    M = M_sun
    params = YukawaParams(alpha=0.0, lambda_m=1.0*AU)
    DeltaY = perihelion_precession_yukawa(a, e, M, params)
    # Tolerancia absoluta en radianes (muy conservadora):
    tol = 1e-12
    rel = abs(DeltaY)
    print(f"[test_yukawa_zero_limit] |DeltaY| = {rel:.3e} rad")
    assert rel < tol

def test_light_deflection_GR_limit() -> None:
    """
    Verifica que la deflexión GR se recupera aproximadamente cuando alpha->0.
    """
    b = R_sun
    M = M_sun
    # To recover alpha_GR from alpha_tot = (1+gamma_inf)*alpha_GR, set gamma_inf = 0.0
    params = YukawaParams(alpha=0.0, lambda_m=1.0*AU)
    alpha_tot, alpha_gr = deflection_angle_yukawa(b, M, params, gamma_inf=0.0) # Changed gamma_inf from 1.0 to 0.0
    rel_err = abs(alpha_tot - alpha_gr) / alpha_gr
    print(f"[test_light_deflection_GR_limit] relative error = {rel_err:.3e}")
    assert rel_err < 1e-2

def test_quad_error_estimate() -> None:
    """
    Comprueba que la integración de una gaussiana simple con quad
    es razonablemente precisa.
    """
    def f(x):
        return np.exp(-x**2)
    res, err = quad(f, -10.0, 10.0, epsabs=0, epsrel=1e-8)
    true_val = np.sqrt(np.pi)
    rel_err = abs(res - true_val) / true_val
    print(f"[test_quad_error_estimate] relative error = {rel_err:.3e}")
    assert rel_err < 1e-6

def run_all_tests() -> None:
    """
    Ejecuta todos los tests rápidos.
    """
    print("Running validation tests...")
    test_yukawa_zero_limit()
    test_light_deflection_GR_limit()
    test_quad_error_estimate()
    print("All tests passed.")

# --- Main: ejecutar tests y generar figuras ---

if __name__ == "__main__":
    run_all_tests()
    print("Generating yukawa_constraints.pdf ...")
    make_yukawa_constraints_plot("yukawa_constraints.pdf")
    print("Generating rho_eff_yukawa.pdf ...")
    plot_rho_eff_yukawa("rho_eff_yukawa.pdf")
    print("Done.")

from google.colab import drive
drive.mount('/content/drive')