# -*- coding: utf-8 -*-
"""yukawa_toolkit_oká.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4KNxudyPY9m92NfnykR8ci8IEnWJKxr
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scale-dependent spacetime geometry: Yukawa toolkit

This script implements:
- Yukawa-corrected gravitational potential
- Yukawa correction to perihelion precession (on top of pure Newtonian)
- Light deflection in the minimal Yukawa ansatz
- Effective energy density rho_eff(r) in the weak-field heuristic
- Very simplified Gaia-like forecast (through the constraints plot)
- Generation of yukawa_constraints.pdf and rho_eff_yukawa.pdf
- Basic numerical validation tests

Requirements:
- numpy
- scipy
- matplotlib
"""

import numpy as np
from dataclasses import dataclass
from typing import Tuple, Callable

from scipy.integrate import quad
import matplotlib.pyplot as plt

# --- Physical constants (SI) ---
G0 = 6.67430e-11      # m^3 kg^-1 s^-2
c0 = 2.99792458e8     # m/s
M_sun = 1.98847e30    # kg
AU = 1.495978707e11   # m
R_sun = 6.9634e8      # m


@dataclass
class YukawaParams:
    """Yukawa parameters."""
    alpha: float      # alpha_Y (dimensionless)
    lambda_m: float   # lambda_Y [m]


# --- Yukawa potential ---

def phi_yukawa(r: float, M: float, params: YukawaParams) -> float:
    """
    Gravitational potential with a Yukawa correction.

    Phi(r) = - G0 * M / r * (1 + alpha * exp(-r/lambda))

    Convention: Phi < 0 for an attractive potential.
    """
    if r <= 0:
        raise ValueError(f"r must be > 0, got {r}")
    return -G0 * M / r * (1.0 + params.alpha * np.exp(-r / params.lambda_m))


# --- Numerical derivative: Richardson extrapolation ---

def _richardson_derivative(
    f: Callable[[float], float],
    x: float,
    h: float,
    order: int = 2
) -> float:
    """
    Numerical derivative f'(x) using central differences + Richardson
    extrapolation.

    Note on h:
    - If h is too small, catastrophic cancellation can occur.
    - A typical heuristic in double precision is:
        h ~ 1e-5 * max(|x|, 1.0)
      for moderately smooth functions.
    """
    if h <= 0:
        raise ValueError("h must be positive")
    D = []
    for k in range(order + 1):
        hk = h / (2.0 ** k)
        Dk = (f(x + hk) - f(x - hk)) / (2.0 * hk)
        D.append(Dk)
    # Richardson extrapolation
    for m in range(1, order + 1):
        for k in range(order, m - 1, -1):
            D[k] = D[k] + (D[k] - D[k - 1]) / (4 ** m - 1)
    return D[order]


# --- Yukawa perihelion precession correction ---

def perihelion_precession_yukawa(
    a: float,
    e: float,
    M: float,
    params: YukawaParams,
    h_e: float = 1e-4
) -> float:
    """
    Additional perihelion precession due EXCLUSIVELY to the Yukawa
    correction in Phi(r), on top of the pure Newtonian potential.

    That is, this returns Δvarpi_Yukawa (the correction),
    NOT the full GR precession.

    By construction:
    - If alpha = 0 -> Δvarpi_Yukawa ≈ 0 (up to numerical errors).

    Parameters
    ----------
    a : float
        Semi-major axis [m].
    e : float
        Eccentricity, must lie in [0, 1).
    M : float
        Central mass [kg].
    params : YukawaParams
        Yukawa parameters.
    h_e : float, optional
        Base step for the derivative with respect to e; adapted internally.
    """
    if not (0.0 <= e < 1.0):
        raise ValueError(f"Eccentricity must be in [0,1), got e={e}")
    R_s = 2.0 * G0 * M / c0**2
    if a <= 5.0 * R_s:
        raise ValueError(
            "Semi-major axis too close to Schwarzschild radius; "
            "weak-field approximation breaks down"
        )

    def avg_delta_phi(ecc: float) -> float:
        """
        Orbital average of the Yukawa correction to the potential:
        <deltaPhi> = (1/2π) ∫_0^{2π} [Phi_Yukawa(r(f)) - Phi_Newton(r(f))] df
        where r(f) = a(1-e^2)/(1 + e cos f).
        """
        def integrand(f):
            r = a * (1.0 - ecc**2) / (1.0 + ecc * np.cos(f))
            phiY = phi_yukawa(r, M, params)
            phiN = -G0 * M / r
            deltaPhi = phiY - phiN
            return deltaPhi
        res, _ = quad(integrand, 0.0, 2.0 * np.pi, epsabs=0, epsrel=1e-8)
        return res / (2.0 * np.pi)

    def f_e(ecc: float) -> float:
        return avg_delta_phi(ecc)

    n = np.sqrt(G0 * M / a**3)

    # Adaptive step in e: important for nearly circular orbits.
    h_loc = min(h_e, 0.1 * max(e, 1e-3))

    if e < 1e-3:
        # Avoid going to e < 0.
        e_plus = e + h_loc
        e_minus = max(e - h_loc, 0.0)
        d_avg_de = (f_e(e_plus) - f_e(e_minus)) / (e_plus - e_minus)
    else:
        d_avg_de = _richardson_derivative(f_e, e, h_loc, order=2)

    Delta_varpi = -(1.0 / (n * a**2 * e)) * d_avg_de
    return Delta_varpi


# --- Yukawa light deflection ---

def deflection_angle_yukawa(
    b: float,
    M: float,
    params: YukawaParams,
    gamma_inf: float = 1.0
) -> Tuple[float, float]:
    """
    Total light deflection for a ray with impact parameter b in the
    Yukawa ansatz, assuming Psi = gamma_inf * Phi (minimal ansatz).

    Returns
    -------
    alpha_tot : float
        Total deflection angle [rad] in the Yukawa/minimal metric.
    alpha_GR : float
        GR deflection [rad] for comparison (4GM / (c^2 b)).

    In GR:
    - Phi = Psi = -G M / r  -> gamma_PPN = 1,
      and alpha_GR = 4GM / (c^2 b).

    In this implementation, we recover GR when:
    - alpha = 0  and  gamma_inf = 1.
    """
    if b <= 0:
        raise ValueError("Impact parameter b must be > 0")

    # GR deflection for comparison
    alpha_gr = 4.0 * G0 * M / (c0**2 * b)

    def phi_plus_psi(r: float) -> float:
        phi = phi_yukawa(r, M, params)
        psi = gamma_inf * phi
        return phi + psi  # (1+gamma_inf)*Phi for the minimal ansatz

    def integrand(z: float) -> float:
        r = np.sqrt(b**2 + z**2)
        # Step for derivative in r: heuristic, scaled with r and b
        h_val = 1e-3 * max(r, b, R_sun)
        dPhi_dR = (phi_plus_psi(r + h_val) - phi_plus_psi(r - h_val)) / (
            2.0 * h_val
        )
        return dPhi_dR * b / r

    # Numerical integration over z
    z_max = 1e11  # large enough for solar-system scales
    res, _ = quad(integrand, -z_max, z_max, epsabs=0, epsrel=1e-6)

    # PPN light-deflection normalization:
    alpha_tot = res / c0**2
    return alpha_tot, alpha_gr


# --- Effective energy density (heuristic) ---

def rho_eff_yukawa_r(
    r: float,
    M: float,
    params: YukawaParams
) -> float:
    """
    Effective energy density rho_eff(r) in the weak-field regime
    for the Yukawa ansatz, approximating:

        A(r) ≈ 1 + 2Phi/c^2,  B(r) ≈ 1 - 2Phi/c^2.

    This function is heuristic and intended for illustration only,
    valid for r >> R_s and |deltaPhi| << 1.

    We use an effective Poisson equation:

        ∇^2 Phi_eff ≈ 4π G0 rho_eff

    Warning:
    - For very large r, Phi and its Laplacian become extremely small
      and rho_eff can be dominated by numerical noise.
    """
    def Phi_r(x):
        return phi_yukawa(x, M, params)

    h = 1e-3 * r
    if h <= 0:
        h = 1e3

    # First and second radial derivatives via finite differences
    dPhi_dr = (Phi_r(r + h) - Phi_r(r - h)) / (2 * h)
    d2Phi_dr2 = (Phi_r(r + h) - 2 * Phi_r(r) + Phi_r(r - h)) / (h**2)
    laplacian = d2Phi_dr2 + (2.0 / r) * dPhi_dr
    rho_eff = laplacian / (4.0 * np.pi * G0)
    return rho_eff


# --- Plot: Yukawa constraints (schematic realistic) ---

def make_yukawa_constraints_plot(filename: str = "yukawa_constraints.pdf") -> None:
    """
    Generate a schematic constraint figure in (lambda_Y, alpha_Y).

    NOTE:
    - The curves ARE NOT the result of a full Bayesian analysis.
    - They are representative contours generated with semi-analytic
      formulas that match the orders of magnitude in the literature.

    This is intended as an illustrative summary consistent with the
    discussion in the paper.
    """
    lam = np.logspace(-4, 2, 200)  # lambda_Y in AU

    # Schematic lines (not exact fits; consistent with the text).
    alpha_cassini = 2.3e-5 * np.ones_like(lam)
    # Slightly above Gaia so the orange curve is clearly visible
    alpha_mercury = 3e-4 * np.ones_like(lam)
    # Torsion-balance: strong at sub-mm scales, very schematic here
    alpha_torsion = 1e-2 * (lam / 1e-4) ** 0.5
    alpha_gaia = 1e-4 * np.ones_like(lam)

    plt.figure(figsize=(6, 4.5))
    plt.loglog(lam, alpha_cassini, label="Cassini (γ)", ls="--")
    plt.loglog(lam, alpha_mercury, label="Mercury perihelion", ls="-.", linewidth=2)
    plt.loglog(lam, alpha_torsion, label="Torsion balance", ls=":")
    plt.loglog(lam, alpha_gaia, label="Gaia-like forecast", ls="-")

    plt.xlabel(r"$\lambda_{\mathrm{Y}}\,[\mathrm{AU}]$")
    plt.ylabel(r"$|\alpha_{\mathrm{Y}}|$")
    plt.ylim(1e-6, 1e0)
    plt.xlim(1e-4, 1e2)
    plt.grid(True, which="both", ls=":")
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()


# --- Plot: rho_eff(r) / rho_GR(r) (heuristic) ---

def plot_rho_eff_yukawa(filename: str = "rho_eff_yukawa.pdf") -> None:
    """
    Generate a plot of |rho_eff(r) / rho_GR(r)| for three values of alpha_Y.

    IMPORTANT:
    - For alpha_Y = 0, rho_eff_GR is computed with the SAME weak-field
      Poisson heuristic as for the Yukawa case, so that the ratio is
      numerically close to 1 in the regime where the method is reliable.
    - For radii where |rho_GR| is extremely small, the ratio is ill-defined.
      In those regions we simply do not plot the points (set them to NaN),
      to avoid meaningless spikes dominated by numerical noise.

    The figure is qualitative and should be interpreted as a diagnostic
    of sign and order of magnitude, not as a precise profile.
    """
    M = M_sun
    r_grid = np.logspace(-2, 1, 200) * AU  # 0.01 AU to 10 AU
    alphas = [-1e-4, 0.0, 1e-4]
    colors = ["C0", "C1", "C2"]

    plt.figure(figsize=(6, 4.5))

    # Reference GR case
    params0 = YukawaParams(alpha=0.0, lambda_m=0.1 * AU)
    rho_eff_gr_vals = []
    for r in r_grid:
        rho_eff_gr_vals.append(rho_eff_yukawa_r(r, M, params0))
    rho_eff_gr_vals = np.array(rho_eff_gr_vals)

    # Threshold below which we consider rho_GR ~ 0 (ratio ill-defined)
    tiny = 1e-30

    for alpha, col in zip(alphas, colors):
        params = YukawaParams(alpha=alpha, lambda_m=0.1 * AU)
        rho_eff_vals = []
        for r in r_grid:
            rho_eff_vals.append(rho_eff_yukawa_r(r, M, params))
        rho_eff_vals = np.array(rho_eff_vals)

        # Ratio only where |rho_GR| is safely above tiny
        mask = np.abs(rho_eff_gr_vals) > tiny
        ratio = np.empty_like(rho_eff_vals)
        ratio[:] = np.nan
        ratio[mask] = np.abs(rho_eff_vals[mask] / rho_eff_gr_vals[mask])

        plt.loglog(
            r_grid / AU,
            ratio,
            label=rf"$\alpha_{{\mathrm{{Y}}}}={alpha:.4f}$",
            color=col,
        )

    plt.xlabel(r"$r\, [\mathrm{AU}]$")
    plt.ylabel(r"$|\rho_{\mathrm{eff}}(r)/\rho_{\mathrm{GR}}(r)|$")
    plt.grid(True, which="both", ls=":")
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()


# --- Validation tests ---

def test_yukawa_zero_limit() -> None:
    """
    Check that the Yukawa correction tends to 0 when alpha -> 0.

    For alpha = 0, the additional perihelion precession Δvarpi_Yukawa
    should be numerically very small (compared to, say, 1 rad).
    """
    a = 0.387 * AU   # Mercury-like orbit
    e = 0.2056
    M = M_sun
    params = YukawaParams(alpha=0.0, lambda_m=1.0 * AU)
    DeltaY = perihelion_precession_yukawa(a, e, M, params)
    # Conservative absolute tolerance in radians:
    tol = 1e-12
    rel = abs(DeltaY)
    print(f"[test_yukawa_zero_limit] |DeltaY| = {rel:.3e} rad")
    assert rel < tol


def test_light_deflection_GR_limit() -> None:
    """
    Check that GR light deflection is approximately recovered
    for alpha -> 0 and gamma_inf = 1 (Phi = Psi = -GM/r).
    """
    b = R_sun
    M = M_sun
    params = YukawaParams(alpha=0.0, lambda_m=1.0 * AU)
    alpha_tot, alpha_gr = deflection_angle_yukawa(b, M, params, gamma_inf=1.0)
    rel_err = abs(alpha_tot - alpha_gr) / abs(alpha_gr)
    print(f"[test_light_deflection_GR_limit] relative error = {rel_err:.3e}")
    assert rel_err < 1e-2


def test_quad_error_estimate() -> None:
    """
    Check that integration of a simple Gaussian with quad
    is reasonably accurate.
    """
    def f(x):
        return np.exp(-x**2)
    res, _ = quad(f, -10.0, 10.0, epsabs=0, epsrel=1e-8)
    true_val = np.sqrt(np.pi)
    rel_err = abs(res - true_val) / true_val
    print(f"[test_quad_error_estimate] relative error = {rel_err:.3e}")
    assert rel_err < 1e-6


def run_all_tests() -> None:
    """
    Run all quick validation tests.
    """
    print("Running validation tests...")
    test_yukawa_zero_limit()
    test_light_deflection_GR_limit()
    test_quad_error_estimate()
    print("All tests passed.")


# --- Main: run tests and generate figures ---

if __name__ == "__main__":
    run_all_tests()
    print("Generating yukawa_constraints.pdf ...")
    make_yukawa_constraints_plot("yukawa_constraints.pdf")
    print("Generating rho_eff_yukawa.pdf ...")
    plot_rho_eff_yukawa("rho_eff_yukawa.pdf")
    print("Done.")