# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iUQBSKWvtxUJuvm5p3NQ-KAN2U-WoAz4
"""

from dataclasses import dataclass
from typing import Tuple, Callable

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import quad
from scipy.ndimage import uniform_filter1d

# -------------------------
# Física básica (valores IAU/CODATA)
# -------------------------

G0 = 6.67430e-11        # m^3 kg^-1 s^-2
c0 = 2.99792458e8       # m/s
M_SUN = 1.98847e30      # kg
AU = 1.495978707e11     # m
R_SUN = 6.957e8         # m


# -------------------------
# Parámetros de Yukawa
# -------------------------

@dataclass
class YukawaParams:
    alpha: float    # fuerza adimensional α_Y
    lambda_m: float # rango λ_Y en metros


# -------------------------
# Potencial y derivadas
# -------------------------

def phi_yukawa(r: float, M: float, params: YukawaParams) -> float:
    """
    Potencial gravitatorio con corrección de Yukawa:

        Phi(r) = - G M / r * (1 + alpha * exp(-r/lambda)).

    Phi < 0 para una interacción atractiva.
    """
    if r <= 0.0:
        raise ValueError(f"r must be > 0, got {r}")
    return -G0 * M / r * (1.0 + params.alpha * np.exp(-r / params.lambda_m))


def _richardson_derivative(
    f: Callable[[float], float],
    x: float,
    h: float,
    order: int = 2
) -> float:
    """
    Derivada f'(x) por diferencias centradas con extrapolación de Richardson.
    """
    if h <= 0.0:
        raise ValueError("h must be positive")

    D = []
    for k in range(order + 1):
        hk = h / (2.0 ** k)
        Dk = (f(x + hk) - f(x - hk)) / (2.0 * hk)
        D.append(Dk)

    for m in range(1, order + 1):
        for k in range(order, m - 1, -1):
            D[k] = D[k] + (D[k] - D[k - 1]) / (4 ** m - 1)
    return D[order]


# -------------------------
# Precesión del perihelio
# -------------------------

def perihelion_precession_yukawa(
    a: float,
    e: float,
    M: float,
    params: YukawaParams,
    h_e: float = 1e-4
) -> float:
    """
    Corrección Yukawa a la precesión del perihelio (Δϖ_Yukawa),
    respecto al potencial puramente newtoniano.

    Devuelve radianes por órbita.
    """
    if not (0.0 <= e < 1.0):
        raise ValueError(f"Eccentricity must be in [0,1), got e={e}")

    R_s = 2.0 * G0 * M / c0**2
    if a <= 5.0 * R_s:
        raise ValueError(
            "Semi-major axis too close to Schwarzschild radius; "
            "weak-field approximation breaks down."
        )

    def avg_delta_phi(ecc: float) -> float:
        def integrand(f):
            r = a * (1.0 - ecc**2) / (1.0 + ecc * np.cos(f))
            phiY = phi_yukawa(r, M, params)
            phiN = -G0 * M / r
            return phiY - phiN

        res, _ = quad(integrand, 0.0, 2.0 * np.pi, epsabs=0.0, epsrel=1e-8)
        return res / (2.0 * np.pi)

    def f_e(ecc: float) -> float:
        return avg_delta_phi(ecc)

    n = np.sqrt(G0 * M / a**3)

    # Paso adaptativo en e (importante para órbitas casi circulares)
    h_loc = min(h_e, 0.1 * max(e, 1e-3))

    if e < 1e-3:
        e_plus = e + h_loc
        e_minus = max(e - h_loc, 0.0)
        d_avg_de = (f_e(e_plus) - f_e(e_minus)) / (e_plus - e_minus)
    else:
        d_avg_de = _richardson_derivative(f_e, e, h_loc, order=2)

    Delta_varpi = -(1.0 / (n * a**2 * e)) * d_avg_de
    return Delta_varpi


# -------------------------
# Deflexión de la luz
# -------------------------

def deflection_angle_yukawa(
    b: float,
    M: float,
    params: YukawaParams,
    gamma_inf: float = 1.0
) -> Tuple[float, float]:
    """
    Ángulo de deflexión para un rayo con parámetro de impacto b
    en el ansatz mínimo (Psi = gamma_inf * Phi).

    Devuelve (alpha_total, alpha_GR) en radianes.
    """
    if b <= 0.0:
        raise ValueError("Impact parameter b must be > 0")

    alpha_gr = 4.0 * G0 * M / (c0**2 * b)

    def phi_plus_psi(r: float) -> float:
        phi = phi_yukawa(r, M, params)
        psi = gamma_inf * phi
        return phi + psi  # (1 + gamma_inf)*Phi en el ansatz mínimo

    def integrand(z: float) -> float:
        r = np.sqrt(b**2 + z**2)
        h_val = 1e-3 * max(r, b, R_SUN)
        dPhi_dR = (phi_plus_psi(r + h_val) - phi_plus_psi(r - h_val)) / (2.0 * h_val)
        return dPhi_dR * b / r

    z_max = 1e11
    res, _ = quad(integrand, -z_max, z_max, epsabs=0.0, epsrel=1e-6)
    alpha_tot = res / c0**2
    return alpha_tot, alpha_gr


# -------------------------
# Densidad efectiva ρ_eff(r)
# -------------------------

def rho_eff_yukawa_r(
    r: float,
    M: float,
    params: YukawaParams
) -> float:
    """
    Densidad efectiva rho_eff(r) en el límite de campo débil,
    usando la ecuación tipo Poisson:

        ∇^2 Phi_eff ≈ 4π G rho_eff.

    Es solo un diagnóstico heurístico para r >> R_s y |delta Phi| << 1.
    """
    if r <= 0.0:
        raise ValueError("r must be > 0")

    def Phi(x: float) -> float:
        return phi_yukawa(x, M, params)

    h = max(1e-6 * r, 1e3)

    dPhi_dr = (Phi(r + h) - Phi(r - h)) / (2.0 * h)
    d2Phi_dr2 = (Phi(r + h) - 2.0 * Phi(r) + Phi(r - h)) / (h**2)
    laplacian = d2Phi_dr2 + (2.0 / r) * dPhi_dr
    rho_eff = laplacian / (4.0 * np.pi * G0)
    return rho_eff


# -------------------------
# Plot 1: plano (λ_Y, α_Y)
# -------------------------

def make_yukawa_constraints_plot(filename: str = "yukawa_constraints.pdf") -> None:
    """
    Gráfico esquemático de restricciones combinadas en el plano
    (lambda_Y, alpha_Y). Las curvas son ilustrativas.
    """
    lam = np.logspace(-4, 2, 200)  # en AU

    alpha_cassini = 2.3e-5 * np.ones_like(lam)
    alpha_mercury = 3.0e-4 * np.ones_like(lam)   # un pelín por encima de Gaia
    alpha_torsion = 2e-3 * (lam / 1e-4) ** 0.5
    alpha_gaia = 1e-4 * np.ones_like(lam)

    plt.figure(figsize=(6.0, 4.5))
    plt.loglog(lam, alpha_cassini, label="Cassini (γ)", ls="--")
    plt.loglog(lam, alpha_mercury, label="Mercury perihelion", ls="-.", lw=1.4)
    plt.loglog(lam, alpha_torsion, label="Torsion balance", ls=":", lw=1.4)
    plt.loglog(lam, alpha_gaia, label="Gaia-like forecast", ls="-")

    plt.xlabel(r"$\lambda_{\rm Y}\,[\mathrm{AU}]$")
    plt.ylabel(r"$|\alpha_{\rm Y}|$")
    plt.ylim(1e-6, 1e0)
    plt.xlim(1e-4, 1e2)
    plt.grid(True, which="both", ls=":")
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()


# -------------------------
# Plot 2: ρ_eff / ρ_GR
# -------------------------

def plot_rho_eff_yukawa(filename: str = "rho_eff_yukawa.pdf") -> None:
    """
    Gráfico del cociente |rho_eff(r)| / |rho_eff,GR(r)| para tres valores
    de α_Y. Para radios donde la referencia GR es numéricamente minúscula
    enmascaramos el cociente y aplicamos un suavizado suave en log-espacio
    para hacer legible la figura.
    """
    M = M_SUN
    r_grid = np.logspace(-2, 1, 200) * AU  # 0.01 AU – 10 AU
    alphas = [-1e-4, 0.0, 1e-4]
    colors = ["C0", "C1", "C2"]
    lambda_m = 0.1 * AU

    params_gr = YukawaParams(alpha=0.0, lambda_m=lambda_m)
    rho_eff_gr_vals = np.array(
        [rho_eff_yukawa_r(r, M, params_gr) for r in r_grid]
    )
    abs_rho_gr = np.abs(rho_eff_gr_vals)
    eps = 1e-40

    plt.figure(figsize=(6.0, 4.5))

    for alpha, col in zip(alphas, colors):
        params = YukawaParams(alpha=alpha, lambda_m=lambda_m)
        rho_eff_vals = np.array(
            [rho_eff_yukawa_r(r, M, params) for r in r_grid]
        )

        ratio = np.empty_like(rho_eff_vals)
        ratio[:] = np.nan

        mask = abs_rho_gr > eps
        if not np.any(mask):
            continue

        if abs(alpha) < 1e-14:
            # Por construcción, rho_eff(alpha=0) ≡ rho_eff_GR
            ratio[mask] = 1.0
        else:
            raw_ratio = np.abs(rho_eff_vals[mask]) / abs_rho_gr[mask]
            log_ratio = np.log10(raw_ratio)
            log_ratio_s = uniform_filter1d(log_ratio, size=7, mode="nearest")
            ratio_s = 10.0 ** log_ratio_s
            ratio[mask] = ratio_s

        plt.loglog(
            r_grid / AU,
            np.abs(ratio),
            label=rf"$\alpha_{{\rm Y}}={alpha:.4f}$",
            color=col,
        )

    plt.xlabel(r"$r\,[\mathrm{AU}]$")
    plt.ylabel(r"$|\rho_{\mathrm{eff}}(r)/\rho_{\mathrm{GR}}(r)|$")
    plt.xlim(1e-2, 1e1)
    plt.ylim(1e-1, 1e4)
    plt.grid(True, which="both", ls=":")
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()


# -------------------------
# Tests de validación rápidos
# -------------------------

def test_yukawa_zero_limit() -> None:
    """
    Comprueba que la corrección Yukawa al perihelio tiende a cero
    cuando alpha -> 0.
    """
    a = 0.387 * AU   # semieje mayor de Mercurio
    e = 0.2056
    M = M_SUN
    params = YukawaParams(alpha=0.0, lambda_m=1.0 * AU)
    DeltaY = perihelion_precession_yukawa(a, e, M, params)
    tol = 1e-12  # rad
    print(f"[test_yukawa_zero_limit] |DeltaY| = {abs(DeltaY):.3e} rad")
    assert abs(DeltaY) < tol


def test_light_deflection_GR_limit() -> None:
    """
    Comprueba que se recupera la deflexión GR (~1%) cuando alpha->0 y
    gamma_inf=1.
    """
    b = R_SUN
    M = M_SUN
    params = YukawaParams(alpha=0.0, lambda_m=1.0 * AU)
    alpha_tot, alpha_gr = deflection_angle_yukawa(b, M, params, gamma_inf=1.0)
    rel_err = abs(alpha_tot - alpha_gr) / abs(alpha_gr)
    print(f"[test_light_deflection_GR_limit] relative error = {rel_err:.3e}")
    assert rel_err < 1e-2


def test_quad_error_estimate() -> None:
    """
    Test de control: integra una gaussiana y comprueba la precisión
    relativa de quad.
    """
    def f(x):
        return np.exp(-x**2)

    res, _ = quad(f, -10.0, 10.0, epsabs=0.0, epsrel=1e-8)
    true_val = np.sqrt(np.pi)
    rel_err = abs(res - true_val) / true_val
    print(f"[test_quad_error_estimate] relative error = {rel_err:.3e}")
    assert rel_err < 1e-6


def run_all_tests() -> None:
    print("Running validation tests...")
    test_yukawa_zero_limit()
    test_light_deflection_GR_limit()
    test_quad_error_estimate()
    print("All tests passed.")


# -------------------------
# Script principal
# -------------------------

if __name__ == "__main__":
    run_all_tests()
    print("Generating yukawa_constraints.pdf ...")
    make_yukawa_constraints_plot("yukawa_constraints.pdf")
    print("Generating rho_eff_yukawa.pdf ...")
    plot_rho_eff_yukawa("rho_eff_yukawa.pdf")
    print("Done.")